SELECT
    cp.[First Name], 
    cp.[Last Name], 
    cp.[Member], 
    cp.[Email Address], 
    cp.[IsRegistered], 
    cp.[User Type], 
    cp.[User Status], 
    cp.[Member Effective Date], 
    cp.[Member Termination Effective Date], 
    cp.[Written Language Preference], 
    cp.[State], 
    cp.[Plan ID], 
    cp.[anoc email], 
    cp.[anoc email date], 
    cp.[anoc print], 
    cp.[anoc print date], 
    cp.[benefit-news print], 
    cp.[benefit-news print date], 
    cp.[benefit-news email], 
    cp.[benefit-news email date], 
    cp.[eob print], 
    cp.[eob print date], 
    cp.[eob email], 
    cp.[eob email date], 
    cp.[partd eob print], 
    cp.[partd eob print date], 
    cp.[partd eob email], 
    cp.[partd eob email date], 
    cp.[benefit-events print], 
    cp.[benefit-events print date], 
    cp.[benefit-events email], 
    cp.[benefit-events email date], 
    cp.[benefit-events none], 
    cp.[benefit-events none date], 
    cp.[general SMS], 
    cp.[general SMS date], 
    cp.[con SCAN SMS], 
    cp.[con SCAN SMS date], 
    cp.[one_on_one SMS], 
    cp.[one_on_one SMS date], 
    cp.[SCAN-club print], 
    cp.[SCAN-club print date], 
    cp.[SCAN-club email], 
    cp.[SCAN-club email date], 
    cp.[SCAN-club none], 
    cp.[SCAN-club none date], 
    cp.[health-reminder print], 
    cp.[health-reminder print date], 
    cp.[health-reminder email], 
    cp.[health-reminder email date], 
    cp.[health-reminder none], 
    cp.[health-reminder none date], 
    cp.[health-events print], 
    cp.[health-events print date], 
    cp.[health-events email], 
    cp.[health-events email date], 
    cp.[health-events none], 
    cp.[health-events none date], 
    cp.[Health-personalized print], 
    cp.[Health-personalized print date], 
    cp.[Health-personalized email], 
    cp.[Health-personalized email date], 
    cp.[Health-personalized none], 
    cp.[Health-personalized none date], 
    cp.[Portal notification email], 
    cp.[Portal notification email date], 
    cp.[Token], 
    cp.[Phone 1 number], 
    cp.[Phone 1 type], 
    cp.[Phone 2 number], 
    cp.[Phone 2 type], 
    cp.[Enrollment Date], 
    cp.[IsRegistered Date], 
    cp.[completedPA]
FROM
    _Subscribers s
Inner Join Communication_Preference as cp on cp.[Email Address] = s.SubscriberKey
And s.Status = 'unsubscribed'
And cp.[anoc print] = 'True'
/* And cp.[User Status] = 'active' */