export const countryOptions = [{label:"Afghanistan",value:"Afghanistan"},
{label:"Albania",value:"Albania"},
{label:"Algeria",value:"Algeria"},
{label:"American Samoa",value:"American Samoa"},
{label:"Angola",value:"Angola"},
{label:"Anguilla",value:"Anguilla"},
{label:"Antartica",value:"Antartica"},
{label:"Antigua and Barbuda",value:"Antigua and Barbuda"},
{label:"Argentina",value:"Argentina"},
{label:"Armenia",value:"Armenia"},
{label:"Aruba",value:"Aruba"},
{label:"Ashmore and Cartier Island",value:"Ashmore and Cartier Island"},
{label:"Australia",value:"Australia"},
{label:"Austria",value:"Austria"},
{label:"Azerbaijan",value:"Azerbaijan"},
{label:"Bahamas",value:"Bahamas"},
{label:"Bahrain",value:"Bahrain"},
{label:"Bangladesh",value:"Bangladesh"},
{label:"Barbados",value:"Barbados"},
{label:"Belarus",value:"Belarus"},
{label:"Belgium",value:"Belgium"},
{label:"Belize",value:"Belize"},
{label:"Benin",value:"Benin"},
{label:"Bermuda",value:"Bermuda"},
{label:"Bhutan",value:"Bhutan"},
{label:"Bolivia",value:"Bolivia"},
{label:"Bosnia and Herzegovina",value:"Bosnia and Herzegovina"},
{label:"Botswana",value:"Botswana"},
{label:"Brazil",value:"Brazil"},
{label:"British Virgin Islands",value:"British Virgin Islands"},
{label:"Brunei",value:"Brunei"},
{label:"Bulgaria",value:"Bulgaria"},
{label:"Burkina Faso",value:"Burkina Faso"},
{label:"Burma",value:"Burma"},
{label:"Burundi",value:"Burundi"},
{label:"Cambodia",value:"Cambodia"},
{label:"Cameroon",value:"Cameroon"},
{label:"Canada",value:"Canada"},
{label:"Cape Verde",value:"Cape Verde"},
{label:"Cayman Islands",value:"Cayman Islands"},
{label:"Central African Republic",value:"Central African Republic"},
{label:"Chad",value:"Chad"},
{label:"Chile",value:"Chile"},
{label:"China",value:"China"},
{label:"Christmas Island",value:"Christmas Island"},
{label:"Clipperton Island",value:"Clipperton Island"},
{label:"Cocos (Keeling) Islands",value:"Cocos (Keeling) Islands"},
{label:"Colombia",value:"Colombia"},
{label:"Comoros",value:"Comoros"},
{label:"Congo, Democratic Republic of the",value:"Congo, Democratic Republic of the"},
{label:"Congo, Republic of the",value:"Congo, Republic of the"},
{label:"Cook Islands",value:"Cook Islands"},
{label:"Costa Rica",value:"Costa Rica"},
{label:"Cote d'Ivoire",value:"Cote d'Ivoire"},
{label:"Croatia",value:"Croatia"},
{label:"Cuba",value:"Cuba"},
{label:"Cyprus",value:"Cyprus"},
{label:"Czech Republic",value:"Czech Republic"},
{label:"Denmark",value:"Denmark"},
{label:"Djibouti",value:"Djibouti"},
{label:"Dominica",value:"Dominica"},
{label:"Dominican Republic",value:"Dominican Republic"},
{label:"Ecuador",value:"Ecuador"},
{label:"Egypt",value:"Egypt"},
{label:"El Salvador",value:"El Salvador"},
{label:"Equatorial Guinea",value:"Equatorial Guinea"},
{label:"Eritrea",value:"Eritrea"},
{label:"Estonia",value:"Estonia"},
{label:"Ethiopia",value:"Ethiopia"},
{label:"Europa Island",value:"Europa Island"},
{label:"Falkland Islands (Islas Malvinas)",value:"Falkland Islands (Islas Malvinas)"},
{label:"Faroe Islands",value:"Faroe Islands"},
{label:"Fiji",value:"Fiji"},
{label:"Finland",value:"Finland"},
{label:"France",value:"France"},
{label:"French Guiana",value:"French Guiana"},
{label:"French Polynesia",value:"French Polynesia"},
{label:"French Southern and Antarctic Lands",value:"French Southern and Antarctic Lands"},
{label:"Gabon",value:"Gabon"},
{label:"Gambia, The",value:"Gambia, The"},
{label:"Gaza Strip",value:"Gaza Strip"},
{label:"Georgia",value:"Georgia"},
{label:"Germany",value:"Germany"},
{label:"Ghana",value:"Ghana"},
{label:"Gibraltar",value:"Gibraltar"},
{label:"Glorioso Islands",value:"Glorioso Islands"},
{label:"Greece",value:"Greece"},
{label:"Greenland",value:"Greenland"},
{label:"Grenada",value:"Grenada"},
{label:"Guadeloupe",value:"Guadeloupe"},
{label:"Guam",value:"Guam"},
{label:"Guatemala",value:"Guatemala"},
{label:"Guernsey",value:"Guernsey"},
{label:"Guinea",value:"Guinea"},
{label:"Guinea-Bissau",value:"Guinea-Bissau"},
{label:"Guyana",value:"Guyana"},
{label:"Haiti",value:"Haiti"},
{label:"Heard Island and McDonald Islands",value:"Heard Island and McDonald Islands"},
{label:"Holy See (Vatican City)",value:"Holy See (Vatican City)"},
{label:"Honduras",value:"Honduras"},
{label:"Hong Kong",value:"Hong Kong"},
{label:"Howland Island",value:"Howland Island"},
{label:"Hungary",value:"Hungary"},
{label:"Iceland",value:"Iceland"},
{label:"India",value:"India"},
{label:"Indonesia",value:"Indonesia"},
{label:"Iran",value:"Iran"},
{label:"Iraq",value:"Iraq"},
{label:"Ireland",value:"Ireland"},
{label:"Ireland, Northern",value:"Ireland, Northern"},
{label:"Israel",value:"Israel"},
{label:"Italy",value:"Italy"},
{label:"Jamaica",value:"Jamaica"},
{label:"Jan Mayen",value:"Jan Mayen"},
{label:"Japan",value:"Japan"},
{label:"Jarvis Island",value:"Jarvis Island"},
{label:"Jersey",value:"Jersey"},
{label:"Johnston Atoll",value:"Johnston Atoll"},
{label:"Jordan",value:"Jordan"},
{label:"Juan de Nova Island",value:"Juan de Nova Island"},
{label:"Kazakhstan",value:"Kazakhstan"},
{label:"Kenya",value:"Kenya"},
{label:"Kiribati",value:"Kiribati"},
{label:"Korea, North",value:"Korea, North"},
{label:"Korea, South",value:"Korea, South"},
{label:"Kuwait",value:"Kuwait"},
{label:"Kyrgyzstan",value:"Kyrgyzstan"},
{label:"Laos",value:"Laos"},
{label:"Latvia",value:"Latvia"},
{label:"Lebanon",value:"Lebanon"},
{label:"Lesotho",value:"Lesotho"},
{label:"Liberia",value:"Liberia"},
{label:"Libya",value:"Libya"},
{label:"Liechtenstein",value:"Liechtenstein"},
{label:"Lithuania",value:"Lithuania"},
{label:"Luxembourg",value:"Luxembourg"},
{label:"Macau",value:"Macau"},
{label:"Macedonia, Former Yugoslav Republic of",value:"Macedonia, Former Yugoslav Republic of"},
{label:"Madagascar",value:"Madagascar"},
{label:"Malawi",value:"Malawi"},
{label:"Malaysia",value:"Malaysia"},
{label:"Maldives",value:"Maldives"},
{label:"Mali",value:"Mali"},
{label:"Malta",value:"Malta"},
{label:"Man, Isle of",value:"Man, Isle of"},
{label:"Marshall Islands",value:"Marshall Islands"},
{label:"Martinique",value:"Martinique"},
{label:"Mauritania",value:"Mauritania"},
{label:"Mauritius",value:"Mauritius"},
{label:"Mayotte",value:"Mayotte"},
{label:"Mexico",value:"Mexico"},
{label:"Micronesia, Federated States of",value:"Micronesia, Federated States of"},
{label:"Midway Islands",value:"Midway Islands"},
{label:"Moldova",value:"Moldova"},
{label:"Monaco",value:"Monaco"},
{label:"Mongolia",value:"Mongolia"},
{label:"Montserrat",value:"Montserrat"},
{label:"Morocco",value:"Morocco"},
{label:"Mozambique",value:"Mozambique"},
{label:"Namibia",value:"Namibia"},
{label:"Nauru",value:"Nauru"},
{label:"Nepal",value:"Nepal"},
{label:"Netherlands",value:"Netherlands"},
{label:"Netherlands Antilles",value:"Netherlands Antilles"},
{label:"New Caledonia",value:"New Caledonia"},
{label:"New Zealand",value:"New Zealand"},
{label:"Nicaragua",value:"Nicaragua"},
{label:"Niger",value:"Niger"},
{label:"Nigeria",value:"Nigeria"},
{label:"Niue",value:"Niue"},
{label:"Norfolk Island",value:"Norfolk Island"},
{label:"Northern Mariana Islands",value:"Northern Mariana Islands"},
{label:"Norway",value:"Norway"},
{label:"Oman",value:"Oman"},
{label:"Pakistan",value:"Pakistan"},
{label:"Palau",value:"Palau"},
{label:"Panama",value:"Panama"},
{label:"Papua New Guinea",value:"Papua New Guinea"},
{label:"Paraguay",value:"Paraguay"},
{label:"Peru",value:"Peru"},
{label:"Philippines",value:"Philippines"},
{label:"Pitcaim Islands",value:"Pitcaim Islands"},
{label:"Poland",value:"Poland"},
{label:"Portugal",value:"Portugal"},
{label:"Puerto Rico",value:"Puerto Rico"},
{label:"Qatar",value:"Qatar"},
{label:"Reunion",value:"Reunion"},
{label:"Romania",value:"Romania"},
{label:"Russia",value:"Russia"},
{label:"Rwanda",value:"Rwanda"},
{label:"Saint Helena",value:"Saint Helena"},
{label:"Saint Kitts and Nevis",value:"Saint Kitts and Nevis"},
{label:"Saint Lucia",value:"Saint Lucia"},
{label:"Saint Pierre and Miquelon",value:"Saint Pierre and Miquelon"},
{label:"Saint Vincent and the Grenadines",value:"Saint Vincent and the Grenadines"},
{label:"Samoa",value:"Samoa"},
{label:"San Marino",value:"San Marino"},
{label:"Sao Tome and Principe",value:"Sao Tome and Principe"},
{label:"Saudi Arabia",value:"Saudi Arabia"},
{label:"Scotland",value:"Scotland"},
{label:"Senegal",value:"Senegal"},
{label:"Seychelles",value:"Seychelles"},
{label:"Sierra Leone",value:"Sierra Leone"},
{label:"Singapore",value:"Singapore"},
{label:"Slovakia",value:"Slovakia"},
{label:"Slovenia",value:"Slovenia"},
{label:"Solomon Islands",value:"Solomon Islands"},
{label:"Somalia",value:"Somalia"},
{label:"South Africa",value:"South Africa"},
{label:"South Georgia and South Sandwich Islands",value:"South Georgia and South Sandwich Islands"},
{label:"Spain",value:"Spain"},
{label:"Spratly Islands",value:"Spratly Islands"},
{label:"Sri Lanka",value:"Sri Lanka"},
{label:"Sudan",value:"Sudan"},
{label:"Suriname",value:"Suriname"},
{label:"Svalbard",value:"Svalbard"},
{label:"Swaziland",value:"Swaziland"},
{label:"Sweden",value:"Sweden"},
{label:"Switzerland",value:"Switzerland"},
{label:"Syria",value:"Syria"},
{label:"Taiwan",value:"Taiwan"},
{label:"Tajikistan",value:"Tajikistan"},
{label:"Tanzania",value:"Tanzania"},
{label:"Thailand",value:"Thailand"},
{label:"Tobago",value:"Tobago"},
{label:"Toga",value:"Toga"},
{label:"Tokelau",value:"Tokelau"},
{label:"Tonga",value:"Tonga"},
{label:"Trinidad",value:"Trinidad"},
{label:"Tunisia",value:"Tunisia"},
{label:"Turkey",value:"Turkey"},
{label:"Turkmenistan",value:"Turkmenistan"},
{label:"Tuvalu",value:"Tuvalu"},
{label:"Uganda",value:"Uganda"},
{label:"Ukraine",value:"Ukraine"},
{label:"United Arab Emirates",value:"United Arab Emirates"},
{label:"United Kingdom",value:"United Kingdom"},
{label:"United States",value:"United States"},
{label:"Uruguay",value:"Uruguay"},
{label:"Uzbekistan",value:"Uzbekistan"},
{label:"Vanuatu",value:"Vanuatu"},
{label:"Venezuela",value:"Venezuela"},
{label:"Vietnam",value:"Vietnam"},
{label:"Virgin Islands",value:"Virgin Islands"},
{label:"Wales",value:"Wales"},
{label:"Wallis and Futuna",value:"Wallis and Futuna"},
{label:"West Bank",value:"West Bank"},
{label:"Western Sahara",value:"Western Sahara"},
{label:"Yemen",value:"Yemen"},
{label:"Yugoslavia",value:"Yugoslavia"},
{label:"Zambia",value:"Zambia"},
{label:"Zimbabwe",value:"Zimbabwe"},
{label:"Montenegro",value:"Montenegro"}
];