export const CONSTANTS = {
  EMPTY_STRING: '',

  PAYMENT_PLAN_MANAGER_LABEL_MODE: 'Payment Plan Mode',
  PAYMENT_PLAN_MANAGER_PLAN_LABEL_STANDARD: 'Standard Plan',
  PAYMENT_PLAN_MANAGER_PLAN_LABEL_FLEXIBLE: 'Flexible Plan',
  PAYMENT_PLAN_MANAGER_PLAN_VALUE_STANDARD: 'Standard',
  PAYMENT_PLAN_MANAGER_PLAN_VALUE_FLEXIBLE: 'Flexible',

  PAYMENT_PLAN_MANAGER_EVENT_TYPE_CHANGE: 'typechange',
  PAYMENT_PLAN_MANAGER_EVENT_PLAN_CHANGE: 'planchange',
  PAYMENT_PLAN_MANAGER_EVENT_DATE_CHANGE: 'datechange',
  PAYMENT_PLAN_MANAGER_EVENT_STD_PLAN_READY: 'standardplanready',
  PAYMENT_PLAN_MANAGER_EVENT_FLEX_PLAN_READY: 'flexibleplanready',
  PAYMENT_PLAN_MANAGER_EVENT_PROCEED_BUTTON_DISABLE: 'disableproceedbuttonevent'
};