import { UNIT_SEARCH_BASE_COLUMNS } from "c/modonEgyptConstants";

export const CONSTANTS = {
  EMPTY_STRING: '',

  UNIT_SEARCH_UNIT_LIST_COLUMNS: [
    {
      label: 'Unit Name',
      fieldName: 'Name',
      type: 'text',
      hideDefaultActions: true,
      minColumnWidth: 200
    },
    {
      label: 'Plot Area',
      fieldName: 'PlotAreasqm__c',
      type: 'number',
      hideDefaultActions: true,
      minColumnWidth: 100
    },
    {
      label: 'No. of Bedrooms',
      fieldName: 'Number_of_Bedrooms__c',
      type: 'number',
      hideDefaultActions: true,
      minColumnWidth: 70
    },
    {
      label: 'Total Price (8 Year plan)',
      fieldName: 'basePriceInCurrency',
      type: 'currency',
      hideDefaultActions: true,
      typeAttributes: {
        currencyCode: { fieldName: 'basePriceCurrencyIsoCode' },
        currencyDisplayAs: 'code',
        minimumFractionDigits: 2,
        maximumFractionDigits: 2
      },
      minColumnWidth: 150
    },
    {
      label: 'Gross Floor Area(GFA)',
      fieldName: 'GrossFloorAreaGFA__c',
      type: 'number',
      hideDefaultActions: true,
      minColumnWidth: 100
    }
  ],

  UNIT_SEARCH_PAYMENT_INSTALLMENTS_COLUMNS: [...UNIT_SEARCH_BASE_COLUMNS],

  UNIT_SEARCH_SPINNER_ALT_LOADING: 'Loading',
  UNIT_SEARCH_ICON_ALT_UNIT_SEARCH: 'Unit Search',
  UNIT_SEARCH_ICON_ALT_CLOSE: 'close',
  UNIT_SEARCH_TITLE_UNIT_SEARCH: 'Unit Search',

  UNIT_SEARCH_BUTTON_NAME_BACK: 'BACK',
  UNIT_SEARCH_BUTTON_NAME_FORWARD: 'FORWARD',
  UNIT_SEARCH_BUTTON_NAME_BOOKING: 'BOOKING',
  UNIT_SEARCH_BUTTON_NAME_BLOCK_REQUEST_EGYPT: 'BLOCKREQUESTEGYPT',
  UNIT_SEARCH_BUTTON_NAME_BLOCK_REQUEST_WITH_FEES: 'BLOCKREQUESTWITHFEES',
  UNIT_SEARCH_BUTTON_NAME_SALES_ORDER: 'SALES ORDER',

  UNIT_SEARCH_BUTTON_LABEL_BACK: 'Back',
  UNIT_SEARCH_BUTTON_LABEL_PROCEED: 'Proceed',
  UNIT_SEARCH_BUTTON_LABEL_BOOK_UNITS: 'Book Unit/s',
  UNIT_SEARCH_BUTTON_LABEL_REQUEST_BLOCK: 'Request a Block',
  UNIT_SEARCH_BUTTON_LABEL_REQUEST_BLOCK_WITH_FEES: 'Request Block with Fees',
  UNIT_SEARCH_BUTTON_LABEL_REFRESH: 'Refresh',
  UNIT_SEARCH_BUTTON_LABEL_GENERATE_SALES_ORDER: 'Generate sales order',
  UNIT_SEARCH_BUTTON_LABEL_SAVE: 'Save',
  UNIT_SEARCH_BUTTON_LABEL_CANCEL: 'Cancel',
  UNIT_SEARCH_BUTTON_LABEL_CLOSE: 'Close',

  UNIT_SEARCH_FILTER_NAME_PROJECTS: 'Projects',
  UNIT_SEARCH_FILTER_NAME_PHASE: 'Phase',
  UNIT_SEARCH_FILTER_NAME_UNIT_TYPE: 'Unit Type',
  UNIT_SEARCH_FILTER_NAME_QUALITY_TYPE: 'Quality Type',
  UNIT_SEARCH_FILTER_NAME_NUMBER_OF_BEDROOMS: 'Number of Bedrooms',
  UNIT_SEARCH_FILTER_NAME_GFA: 'GFA (Gross Floor Area)',
  UNIT_SEARCH_FILTER_NAME_FLOOR: 'Floor',
  UNIT_SEARCH_FILTER_NAME_CURRENCY: 'Currency',

  UNIT_SEARCH_FILTER_LABEL_PROJECTS: 'Projects',
  UNIT_SEARCH_FILTER_LABEL_PHASE: 'Phase',
  UNIT_SEARCH_FILTER_LABEL_UNIT_TYPE: 'Unit Type',
  UNIT_SEARCH_FILTER_LABEL_QUALITY_TYPE: 'Quality Type',
  UNIT_SEARCH_FILTER_LABEL_NUMBER_OF_BEDROOMS: 'Number of Bedrooms',
  UNIT_SEARCH_FILTER_LABEL_GFA: 'GFA (Gross Floor Area)',
  UNIT_SEARCH_FILTER_LABEL_FLOOR: 'Floor',
  UNIT_SEARCH_FILTER_LABEL_UNIT_NAME: 'Unit Name',
  UNIT_SEARCH_FILTER_PLACEHOLDER_UNIT_NAME: 'Enter Unit Name',
  UNIT_SEARCH_FILTER_LABEL_CURRENCY: 'Currency',

  UNIT_SEARCH_TABLE_HEADER_UNIT_NAME: 'Unit Name',
  UNIT_SEARCH_TABLE_HEADER_PLOT_AREA: 'Plot Area',
  UNIT_SEARCH_TABLE_HEADER_NO_OF_BEDROOMS: 'No. of Bedrooms',
  UNIT_SEARCH_TABLE_HEADER_TOTAL_PRICE_8_YEAR: 'Total Price (8 Year plan)',
  UNIT_SEARCH_TABLE_HEADER_GFA: 'Gross Floor Area(GFA)',

  UNIT_SEARCH_CARD_NO_PAYMENT_PLAN: 'No payment plan is available for this unit.',

  UNIT_SEARCH_CONFIRM_CHECKBOX_LABEL: 'Confirm all selection',

  UNIT_SEARCH_CARD_TITLE_SALES_ORDER_DETAILS: 'Sales order details',
  UNIT_SEARCH_LABEL_UNIT_NAME_COLON: 'Unit name :',
  UNIT_SEARCH_LABEL_PHASE_NAME_COLON: 'Phase name :',
  UNIT_SEARCH_LABEL_PROJECT_NAME_COLON: 'Project name :',
  UNIT_SEARCH_LABEL_PRICE_COLON: 'Price :',
  UNIT_SEARCH_LABEL_SELECTED_PAYMENT_PLAN_BOLD: 'Selected Payment Plan :',
  UNIT_SEARCH_LABEL_MAINTENANCE_FEES_COLON: 'Maintenance Fees :',
  UNIT_SEARCH_LABEL_EXACT_BOOKING_DATE_BOLD: 'Exact Booking Date :',

  UNIT_SEARCH_INSTALL_TABLE_HEADER_INSTALLMENT_NUM: 'Installment #',
  UNIT_SEARCH_INSTALL_TABLE_HEADER_MILESTONE: 'Milestone',
  UNIT_SEARCH_INSTALL_TABLE_HEADER_INSTALLMENT_PCT: 'Installment Percentage',
  UNIT_SEARCH_INSTALL_TABLE_HEADER_MAINTENANCE_FEES: 'Maintenance Fees',
  UNIT_SEARCH_INSTALL_TABLE_HEADER_INSTALLMENT_AMOUNT: 'Installment amount',

  UNIT_SEARCH_INSTALL_TABLE_HEADER_INSTALLMENT_DATE: 'Installment Date',

  UNIT_SEARCH_MODAL_TITLE_BLOCK_UNIT_DETAILS: 'Block Unit Details',
  UNIT_SEARCH_MODAL_LABEL_COMMENT: 'Comment',

  UNIT_SEARCH_LIGHTNING_CARD_VARIANT_NARROW: 'Narrow',
  UNIT_SEARCH_TAB_DATA_TARGET_TYPE: 'tab',

  UNIT_SEARCH_STEP_LABEL_UNIT_SELECTION: 'Unit Selection',
  UNIT_SEARCH_STEP_LABEL_PAYMENT_SELECTION: 'Payment Selection',
  UNIT_SEARCH_STEP_LABEL_BOOK_UNITS: 'Book Unit(s)',

  UNIT_SEARCH_PLAN_LABEL_STANDARD: 'Standard Plan',
  UNIT_SEARCH_PLAN_LABEL_FLEXIBLE: 'Flexible Plan',
  UNIT_SEARCH_PLAN_VALUE_STANDARD: 'Standard',
  UNIT_SEARCH_PLAN_VALUE_FLEXIBLE: 'Flexible',
  UNIT_SEARCH_PLAN_DISPLAY_FLEXIBLE_PAYMENT: 'Flexible Payment Plan',

  UNIT_SEARCH_TOAST_TITLE_UNITS: 'Units',
  UNIT_SEARCH_TOAST_MSG_NO_UNITS_FILTER: 'No unit available for selected filter criteria ',
  UNIT_SEARCH_TOAST_TITLE_ERROR_BANG: 'Error!',
  UNIT_SEARCH_TOAST_MSG_PAYMENT_PLAN_NOT_SELECTED_PREFIX: 'Payment plan is not selected for ',
  UNIT_SEARCH_TOAST_MSG_PAYMENT_PLAN_NOT_SELECTED_SUFFIX: ' unit.',
  UNIT_SEARCH_TOAST_TITLE_UNIT_NO_VALUE: 'Unit does not have value',
  UNIT_SEARCH_TOAST_MSG_UNIT_PRICE_ZERO: 'Unit price cannot be zero for Booking or Blocking',
  UNIT_SEARCH_TOAST_TITLE_SUCCESS: 'Success',
  UNIT_SEARCH_TOAST_MSG_SALES_ORDER_CREATED: 'Sales order created successfully.',
  UNIT_SEARCH_TOAST_TITLE_ERROR: 'Error',
  UNIT_SEARCH_TOAST_MSG_REVIEW_ERRORS: 'Please review all the errors',
  UNIT_SEARCH_TOAST_MSG_BLOCK_SUBMITTED: 'Block on the selected units are submitted for approval.',
  UNIT_SEARCH_TOAST_TITLE_MISSING_NATIONALITY: 'Missing Nationality',
  UNIT_SEARCH_TOAST_TITLE_MISSING_DOCUMENTS: 'Missing Documents',
  UNIT_SEARCH_TOAST_MSG_DOC_CHECK_ERROR: 'An error occurred while checking documents.',
  UNIT_SEARCH_TOAST_MSG_DOCS_REQUIRED_SUFFIX: ' are required to be uploaded before blocking the unit.',

  UNIT_SEARCH_APEX_RESPONSE_SUCCESS: 'Success',
  UNIT_SEARCH_LAST_PAGE_NAME_BOOKING: 'Booking',

  UNIT_SEARCH_PAYMENT_KEYWORD_8_YEAR: '8 year',
  UNIT_SEARCH_PAYMENT_KEYWORD_8_YEARS: '8 Years',
  UNIT_SEARCH_PAYMENT_KEYWORD_CASH: 'cash',
  UNIT_SEARCH_PAYMENT_KEYWORD_6_YEAR: '6 year',
  UNIT_SEARCH_PAYMENT_KEYWORD_4_YEAR: '4 year',
  UNIT_SEARCH_PAYMENT_PLAN_KEY_CASH: 'cash',

  UNIT_SEARCH_CURRENCY_EGP: 'EGP',
  UNIT_SEARCH_CURRENCY_USD: 'USD',
  UNIT_SEARCH_CURRENCY_AED: 'AED',

  UNIT_SEARCH_NATIONALITY_EGYPT: 'Egypt',
  UNIT_SEARCH_BLOCKING_HOURS_120: '120',
  UNIT_SEARCH_BLOCKING_HOURS_24: '24',

  UNIT_SEARCH_DOC_CHECK_NATIONALITY_REQUIRED_PHRASE: 'Nationality is required for Account.',

  UNIT_SEARCH_SELECTED_UNIT_KEY_SELECTION_STATUS: 'selectionStatus',
  UNIT_SEARCH_SELECTED_UNIT_KEY_PAYMENT_DETAILS: 'paymentDetails',
  UNIT_SEARCH_SELECTED_UNIT_KEY_UNIT_ID: 'unitId',
  UNIT_SEARCH_SELECTED_UNIT_KEY_UNIT_NAME: 'unitName',
  UNIT_SEARCH_SELECTED_UNIT_KEY_PROJECT_ID: 'projectId',
  UNIT_SEARCH_SELECTED_UNIT_KEY_PROJECT_NAME: 'projectName',
  UNIT_SEARCH_SELECTED_UNIT_KEY_PRICE: 'price',
  UNIT_SEARCH_SELECTED_UNIT_KEY_PHASE_NAME: 'phaseName',
  UNIT_SEARCH_SELECTED_UNIT_KEY_PHASE_ID: 'phaseId',
  UNIT_SEARCH_SELECTED_UNIT_KEY_PAYMENT_PLAN_TYPE: 'paymentPlanType',
  UNIT_SEARCH_SELECTED_UNIT_KEY_IS_STANDARD_PLAN: 'isStandardPlan',
  UNIT_SEARCH_SELECTED_UNIT_KEY_IS_FLEXIBLE_PLAN: 'isFlexiblePlan',

  UNIT_SEARCH_BUTTON_NAME_BACK: 'BACK',
  UNIT_SEARCH_BUTTON_NAME_FORWARD: 'FORWARD',
  UNIT_SEARCH_BUTTON_NAME_BOOKING: 'BOOKING',
  UNIT_SEARCH_BUTTON_NAME_BLOCK_REQUEST_EGYPT: 'BLOCKREQUESTEGYPT',
  UNIT_SEARCH_BUTTON_NAME_BLOCK_REQUEST_WITH_FEES: 'BLOCKREQUESTWITHFEES'
};