import { LightningElement, track } from 'lwc';
import getBusinessProcess from '@salesforce/apex/HandOverSearchController.getBusinessProcess';
import sendNotifications from '@salesforce/apex/HandOverSearchController.sendNotifications';
import updateHandoverPhasing from '@salesforce/apex/HandOverSearchController.updateHandoverPhasing';
import updateKARUser from '@salesforce/apex/HandOverSearchController.updateKARUser';
import { ShowToastEvent } from 'lightning/platformShowToastEvent';
import getBusinessProcessByUnitNames from '@salesforce/apex/HandOverSearchController.getBusinessProcessByUnitNames';
import updateHandoverDetailZone from '@salesforce/apex/HandOverSearchController.updateHandoverDetailZone';
import uploadBCCLetter from '@salesforce/apex/HandOverSearchController.uploadBCCLetter';

export default class SalesBookingSearch extends LightningElement {

    projectId;
    phaseId;
    salesOrderId;
    unitId;
    modalHeader;
    currentAction;

    showModal = false;
    hideCheckboxColumn = false;

    /* Handover Phasing Fields */
    phasePicklistValue = '';
    handoverDate;
    expectedHandoverDate;
    selectedUserId;
    selectedHandoverPhase;

    @track columns = [];
    @track records = [];
    @track allRecords = [];

    isLoading = false;
    showTable = false;
    showNoRecords = false;

    pageNumber = 1;
    pageSize = 20;
    totalPages = 0;

    /*
     * Used only to ignore the automatic row-selection
     * event generated by lightning-datatable when the
     * page/data changes.
     */
    isChangingPage = false;

    /* =========================================================
   CSV UPLOAD
   ========================================================= */

isCsvSearch = false;

@track missingUnitNames = [];

csvTotalUnits = 0;
csvFoundUnits = 0;

//update Phase
showUpdatePhasingModal = false;
selectedZone = '';
@track csvRecords = [];

get zoneOptions() {

    const options = [];

    for (let i = 1; i <= 20; i++) {

        options.push({
            label: `Zone ${i}`,
            value: `Zone ${i}`
        });

    }

    return options;
}

//BCC Letter Variables

showBCCLetterModal = false;

bccUploadRecordId = null;

bccUploadedFileName = null;

bccAcceptedFormats = [
    '.pdf',
    '.doc',
    '.docx',
    '.jpg',
    '.jpeg',
    '.png'
];

get updatePhasingDisabled() {

    return !this.selectedZone || this.isLoading;
}

get csvMissingUnitsCount() {
    return this.missingUnitNames.length;
}

get showMissingUnits() {
    return this.missingUnitNames.length > 0;
}

    /*
     * =========================================================
     * SELECTED ROWS
     * =========================================================
     *
     * isChecked on each record is the SINGLE SOURCE OF TRUTH.
     *
     * We do NOT maintain selectedRowsByPage anymore.
     */

    get selectedRowIds() {
        return this.allRecords
            .filter(row => row.isChecked === true)
            .map(row => row.Id);
    }

    /*
     * This is what lightning-datatable uses for selected-rows.
     *
     * It only returns IDs for the records currently displayed
     * on the current page.
     */
    get selectedRows() {
        return this.records
            .filter(row => row.isChecked === true)
            .map(row => row.Id);
    }

    get topButtonsDisabled() {
        return this.selectedRowIds.length === 0;
    }

    /* =========================================================
       FILTER HANDLERS
       ========================================================= */

    handleProjectSelection(event) {
        this.projectId = event.detail;
    }

    handleProjectClear() {
        this.projectId = null;
    }

    handlePhaseSelection(event) {
        this.phaseId = event.detail;
    }

    handlePhaseClear() {
        this.phaseId = null;
    }

    handleSalesOrderSelection(event) {
        this.salesOrderId = event.detail;
    }

    handleSalesOrderClear() {
        this.salesOrderId = null;
    }

    handleUnitSelection(event) {
        this.unitId = event.detail;
    }

    handleUnitClear() {
        this.unitId = null;
    }

    handleHandoverPhaseChange(event) {
        this.selectedHandoverPhase = event.detail.value;
    }

    /* =========================================================
       SEARCH
       ========================================================= */

    async handleSearch() {

        if (
            !this.projectId &&
            !this.phaseId &&
            !this.salesOrderId &&
            !this.unitId &&
            !this.selectedHandoverPhase
        ) {
            this.dispatchEvent(
                new ShowToastEvent({
                    title: 'Filter Required',
                    message: 'Please select at least one filter',
                    variant: 'warning'
                })
            );

            return;
        }

        this.isLoading = true;
        this.showTable = false;
        this.showNoRecords = false;

        try {

            const result = await getBusinessProcess({
                projectId: this.projectId,
                phaseId: this.phaseId,
                salesOrderId: this.salesOrderId,
                unitId: this.unitId,
                handoverPhase: this.selectedHandoverPhase
            });

            /*
             * IMPORTANT:
             *
             * Add isChecked = false to every record.
             */
            this.allRecords = (result.records || []).map(row => ({
                ...row,
                isChecked: false
            }));

            this.columns = result.columns;

            if (this.allRecords.length > 0) {

                this.pageNumber = 1;

                this.totalPages = Math.ceil(
                    this.allRecords.length / this.pageSize
                );

                this.updatePageData();

                this.showTable = true;

            } else {

                this.showNoRecords = true;
            }

        } catch (error) {

            console.error('Search Error:', error);

            this.showToast(
                'Error',
                error?.body?.message || 'An error occurred while searching.',
                'error'
            );

        } finally {

            this.isLoading = false;
        }
    }

    /* =========================================================
       PAGE DATA
       ========================================================= */

    updatePageData() {

        const start = (this.pageNumber - 1) * this.pageSize;
        const end = start + this.pageSize;

        /*
         * Set this BEFORE changing records.
         *
         * lightning-datatable may automatically fire
         * rowselection when selected-rows changes.
         */
        this.isChangingPage = true;

        this.records = this.allRecords.slice(start, end);

        console.log(
            'PAGE:',
            this.pageNumber
        );

        console.log(
            'CURRENT PAGE RECORDS:',
            JSON.stringify(
                this.records.map(row => ({
                    Id: row.Id,
                    isChecked: row.isChecked
                }))
            )
        );

        console.log(
            'CURRENT PAGE SELECTED:',
            JSON.stringify(this.selectedRows)
        );

        console.log(
            'ALL SELECTED:',
            JSON.stringify(this.selectedRowIds)
        );

        /*
         * Give lightning-datatable time to render the new page
         * and process selected-rows.
         */
        setTimeout(() => {
            this.isChangingPage = false;

            console.log(
                'Page rendering completed:',
                this.pageNumber
            );
        }, 300);
    }

    /* =========================================================
       NEXT PAGE
       ========================================================= */

    handleNext() {

        if (this.pageNumber < this.totalPages) {

            this.pageNumber++;

            this.updatePageData();
        }
    }

    /* =========================================================
       PREVIOUS PAGE
       ========================================================= */

    handlePrevious() {

        if (this.pageNumber > 1) {

            this.pageNumber--;

            this.updatePageData();
        }
    }

    get disablePrevious() {
        return this.pageNumber === 1;
    }

    get disableNext() {
        return this.pageNumber === this.totalPages;
    }

    /* =========================================================
       ROW SELECTION
       ========================================================= */

    handleRowSelection(event) {

        /*
         * Ignore the automatic event generated when changing
         * pages / changing selected-rows.
         */
        if (this.isChangingPage) {

            console.log(
                'Ignoring automatic page-change selection event'
            );

            return;
        }

        const selectedIds = new Set(
            event.detail.selectedRows.map(row => row.Id)
        );

        console.log(
            'USER SELECTED ON PAGE:',
            this.pageNumber,
            JSON.stringify([...selectedIds])
        );

        /*
         * Update isChecked ONLY for records on the current page.
         *
         * Records on other pages remain untouched.
         */
        const currentPageIds = new Set(
            this.records.map(row => row.Id)
        );

        this.allRecords = this.allRecords.map(row => {

            if (currentPageIds.has(row.Id)) {

                return {
                    ...row,
                    isChecked: selectedIds.has(row.Id)
                };
            }

            return row;
        });

        /*
         * Refresh current page references.
         */
        const start = (this.pageNumber - 1) * this.pageSize;
        const end = start + this.pageSize;

        this.records = this.allRecords.slice(start, end);

        console.log(
            'CURRENT PAGE isChecked:',
            JSON.stringify(
                this.records.map(row => ({
                    Id: row.Id,
                    isChecked: row.isChecked
                }))
            )
        );

        console.log(
            'ALL SELECTED:',
            JSON.stringify(this.selectedRowIds)
        );
    }

    /* =========================================================
       CLEAR
       ========================================================= */

    handleClear() {

        this.projectId = null;
        this.phaseId = null;
        this.salesOrderId = null;
        this.unitId = null;
        this.selectedHandoverPhase = null;

        this.records = [];
        this.allRecords = [];

        this.pageNumber = 1;
        this.totalPages = 0;

        this.isChangingPage = false;

        this.template
            .querySelectorAll('c-generic-lookup-lwc')
            .forEach(lookup => {
                lookup.clearLookup?.();
            });

        this.showTable = false;
        this.showNoRecords = false;

        //nsv new
        this.isCsvSearch = false;
        this.missingUnitNames = [];
        this.csvTotalUnits = 0;
        this.csvFoundUnits = 0;
    }

    /* =========================================================
       TOP BUTTONS ACTIONS
       ========================================================= */

    handleHandoverPhasing() {

        this.currentAction = 'Handover Phasing';
        this.modalHeader = 'Handover Phasing';
        this.showModal = true;
    }

    handleReassignKar() {

        this.currentAction = 'Reassign KAR';
        this.modalHeader = 'Reassign KAR';
        this.showModal = true;
    }

    handleAssignKar() {

        this.currentAction = 'Assign KAR';
        this.modalHeader = 'Assign KAR / Initiate CHO';
        this.showModal = true;
    }

    handleFinanceVerification() {

        this.handleClear();
    }

    /* =========================================================
       PHASE PICKLIST
       ========================================================= */

    get phasePicklistOptions() {

        return [
            { label: 'Phase 1', value: 'Phase 1' },
            { label: 'Phase 2', value: 'Phase 2' },
            { label: 'Phase 3', value: 'Phase 3' },
            { label: 'Phase 4', value: 'Phase 4' },
            { label: 'Phase 5', value: 'Phase 5' },
            { label: 'Phase 6', value: 'Phase 6' },
            { label: 'Phase 7', value: 'Phase 7' },
            { label: 'Phase 8', value: 'Phase 8' },
            { label: 'Phase 9', value: 'Phase 9' },
            { label: 'Phase 10', value: 'Phase 10' }
        ];
    }

    /* =========================================================
       HANDOVER PHASING
       ========================================================= */

    handleHandoverPhasings(event) {

        const field = event.target.label;

        if (field === 'Handover Date') {

            this.handoverDate = event.detail.value;

        } else if (field === 'Expected Handover Date') {

            this.expectedHandoverDate = event.detail.value;

        } else if (field === 'Phase') {

            this.phasePicklistValue = event.detail.value;
        }
    }

    handleUserSelect(event) {

        this.selectedUserId = event.detail.recordId;
    }

    get isHandoverPhasing() {

        return this.currentAction === 'Handover Phasing';
    }

    get isAssignKar() {

        return this.currentAction === 'Assign KAR';
    }

    get isReassignKar() {

        return this.currentAction === 'Reassign KAR';
    }

    /* =========================================================
       SAVE MODAL
       ========================================================= */

    async handleSaveModal() {

        if (this.currentAction === 'Handover Phasing') {

            if (!this.phasePicklistValue) {

                this.showToast(
                    'Validation',
                    'Please select a Phase.',
                    'warning'
                );

                return;
            }

            if (!this.handoverDate) {

                this.showToast(
                    'Validation',
                    'Please select a Handover Date.',
                    'warning'
                );

                return;
            }

            if (!this.expectedHandoverDate) {

                this.showToast(
                    'Validation',
                    'Please select an Expected Handover Date.',
                    'warning'
                );

                return;
            }

            try {

                const response = await updateHandoverPhasing({
                    businessProcessIds: this.selectedRowIds,
                    handoverDate: this.handoverDate,
                    expectedHandoverDate: this.expectedHandoverDate,
                    phase: this.phasePicklistValue
                });

                this.showToast(
                    response.success ? 'Success' : 'Error',
                    response.message,
                    response.success ? 'success' : 'error'
                );

                if (response.success) {

                    this.showModal = false;
                    this.handoverDate = null;
                    this.expectedHandoverDate = null;
                    this.phasePicklistValue = '';

                    this.handleClear();
                }

            } catch (error) {

                this.showToast(
                    'Error',
                    error?.body?.message ||
                    'An unexpected error occurred.',
                    'error'
                );
            }

        } else if (
            this.currentAction === 'Assign KAR' ||
            this.currentAction === 'Reassign KAR'
        ) {

            if (!this.selectedUserId) {

                this.showToast(
                    'Validation',
                    'Please select a User.',
                    'warning'
                );

                return;
            }

            try {

                const response = await updateKARUser({
                    businessProcessIds: this.selectedRowIds,
                    userId: this.selectedUserId
                });

                this.showToast(
                    response.success ? 'Success' : 'Error',
                    response.message,
                    response.success ? 'success' : 'error'
                );

                if (response.success) {

                    this.showModal = false;
                    this.selectedUserId = null;

                    this.handleClear();
                }

            } catch (error) {

                this.showToast(
                    'Error',
                    error?.body?.message ||
                    'An unexpected error occurred.',
                    'error'
                );
            }
        }
    }

    handleCloseModal() {

        this.showModal = false;
    }

    /* =========================================================
       NOTIFICATIONS
       ========================================================= */

    async handleMenuSelect(event) {

        const action = event.detail.value;

        let notificationType;

        if (action === 'handover') {

            notificationType = 'Handover Completion';

        } else if (action === 'orientation') {

            notificationType = 'Home Orientation';

        } else if (action === 'handover phasing') {

            notificationType = 'Handover Phasing';
        }

        if (!this.validateNotificationRequest(notificationType)) {
            return;
        }

        try {

            const response = await sendNotifications({
                businessProcessIds: this.selectedRowIds,
                notificationType
            });

            this.showToast(
                response.success ? 'Success' : 'Error',
                response.message,
                response.success ? 'success' : 'error'
            );

            if (response.success) {

                this.handleClear();
            }

        } catch (error) {

            this.showToast(
                'Error',
                error?.body?.message ||
                'An unexpected error occurred.',
                'error'
            );
        }
    }

    validateNotificationRequest(notificationType) {

        if (!notificationType) {

            this.showToast(
                'Warning',
                'Please select a valid notification type.',
                'warning'
            );

            return false;
        }

        if (
            !this.selectedRowIds ||
            this.selectedRowIds.length === 0
        ) {

            this.showToast(
                'Warning',
                'Please select at least one record.',
                'warning'
            );

            return false;
        }

        return true;
    }

    /* =========================================================
       TOAST
       ========================================================= */

    showToast(title, message, variant) {

        this.dispatchEvent(
            new ShowToastEvent({
                title: title,
                message: message,
                variant: variant
            })
        );
    }

    handleUploadCsv() {

    const fileInput = this.template.querySelector(
        '.csv-file-input'
    );

    if (fileInput) {
        fileInput.value = null;
        fileInput.click();
    }
}

async handleCsvFileChange(event) {

    const file = event.target.files[0];

    if (!file) {
        return;
    }

    if (!file.name.toLowerCase().endsWith('.csv')) {

        this.showToast(
            'Invalid File',
            'Please upload a CSV file only.',
            'error'
        );

        return;
    }

    this.isLoading = true;

    try {

        const csvText = await this.readCsvFile(file);

        const unitNames = this.parseUnitNamesFromCsv(csvText);

        if (!unitNames || unitNames.length === 0) {

            this.showToast(
                'Invalid CSV',
                'No Unit Name values were found in the CSV file.',
                'warning'
            );

            return;
        }

        console.log(
            'CSV Unit Names:',
            JSON.stringify(unitNames)
        );

        this.csvTotalUnits = unitNames.length;

        const result = await getBusinessProcessByUnitNames({
            unitNames: unitNames
        });

        console.log(
            'CSV Search Result:',
            JSON.stringify(result)
        );

        this.processCsvResult(result);

    } catch (error) {

        console.error(
            'CSV Upload Error:',
            error
        );

        this.showToast(
            'Error',
            error?.body?.message ||
            'An error occurred while processing the CSV file.',
            'error'
        );

    } finally {

        this.isLoading = false;

        /*
         * Clear file input so the same file can be uploaded again.
         */
        event.target.value = null;
    }
}

readCsvFile(file) {

    return new Promise((resolve, reject) => {

        const reader = new FileReader();

        reader.onload = () => {
            resolve(reader.result);
        };

        reader.onerror = () => {
            reject(
                new Error('Unable to read CSV file.')
            );
        };

        reader.readAsText(file);
    });
}

parseUnitNamesFromCsv(csvText) {

    if (!csvText) {
        return [];
    }

    /*
     * Remove BOM if present.
     */
    csvText = csvText.replace(/^\uFEFF/, '');

    const lines = csvText
        .split(/\r?\n/)
        .map(line => line.trim())
        .filter(line => line.length > 0);

    if (lines.length < 2) {
        return [];
    }

    const headers = this.parseCsvLine(lines[0]);

    const normalizedHeaders = headers.map(header =>
        header
            .trim()
            .replace(/^["']|["']$/g, '')
            .toLowerCase()
            .replace(/\s+/g, '')
    );

    const unitNameIndex = normalizedHeaders.findIndex(
        header =>
            header === 'unitname' ||
            header === 'unit'
    );

    if (unitNameIndex === -1) {

        this.showToast(
            'Invalid CSV',
            'CSV must contain a "Unit Name" column.',
            'error'
        );

        return [];
    }

    const unitNames = [];

    for (let i = 1; i < lines.length; i++) {

        const values = this.parseCsvLine(lines[i]);

        if (
            values.length <= unitNameIndex
        ) {
            continue;
        }

        let unitName = values[unitNameIndex];

        if (!unitName) {
            continue;
        }

        unitName = unitName
            .trim()
            .replace(/^["']|["']$/g, '')
            .trim();

        if (unitName) {
            unitNames.push(unitName);
        }
    }

    /*
     * Remove duplicates while preserving order.
     */
    return [
        ...new Set(unitNames)
    ];
}

parseCsvLine(line) {

    const result = [];

    let current = '';
    let insideQuotes = false;

    for (let i = 0; i < line.length; i++) {

        const char = line[i];

        if (char === '"') {

            if (
                insideQuotes &&
                line[i + 1] === '"'
            ) {

                current += '"';
                i++;

            } else {

                insideQuotes = !insideQuotes;
            }

        } else if (
            char === ',' &&
            !insideQuotes
        ) {

            result.push(current);
            current = '';

        } else {

            current += char;
        }
    }

    result.push(current);

    return result;
}

processCsvResult(result) {

    const returnedRecords =
        result?.records || [];

    const missingUnits =
        result?.missingUnitNames || [];

    /*
     * =====================================================
     * STORE MISSING UNIT NAMES
     * =====================================================
     */

    this.missingUnitNames = [
        ...missingUnits
    ];

    /*
     * =====================================================
     * STORE FOUND RECORDS
     * =====================================================
     */

    this.allRecords = returnedRecords.map(row => ({
        ...row,
        isChecked: false
    }));

    this.csvFoundUnits =
        result?.foundUnitCount ||
        this.allRecords.length;

    /*
     * =====================================================
     * CSV SEARCH MODE
     * =====================================================
     */

    this.isCsvSearch = true;

    /*
     * Use the same columns returned by Apex.
     */
    this.columns = result?.columns || [];

    /*
     * =====================================================
     * PAGINATION
     * =====================================================
     */

    this.pageNumber = 1;

    if (this.allRecords.length > 0) {

        this.totalPages = Math.ceil(
            this.allRecords.length /
            this.pageSize
        );

        this.updatePageData();

        this.showTable = true;
        this.showNoRecords = false;

    } else {

        this.records = [];
        this.totalPages = 0;
        this.showTable = false;
        this.showNoRecords = true;
    }

    /*
     * =====================================================
     * MESSAGE
     * =====================================================
     */

    if (
        this.allRecords.length > 0 &&
        this.missingUnitNames.length > 0
    ) {

        this.showToast(
            'Completed',
            `${this.csvFoundUnits} unit(s) found. ` +
            `${this.missingUnitNames.length} unit(s) not found.`,
            'warning'
        );

    } else if (
        this.allRecords.length > 0
    ) {

        this.showToast(
            'Success',
            `${this.csvFoundUnits} unit(s) found.`,
            'success'
        );

    } else {

        this.showToast(
            'No Records',
            'No Business Process / Handover records were found for the uploaded Unit Names.',
            'warning'
        );
    }
}

handleUpdatePhasing() {

    if (!this.selectedRowIds || this.selectedRowIds.length === 0) {

        this.showToast(
            'Warning',
            'Please select at least one Unit.',
            'warning'
        );

        return;
    }

    this.selectedZone = '';

    this.showUpdatePhasingModal = true;
}

handleZoneChange(event) {

    this.selectedZone = event.detail.value;
}

handleCloseUpdatePhasingModal() {

    if (this.isLoading) {
        return;
    }

    this.showUpdatePhasingModal = false;
    this.selectedZone = '';
}

async handleUpdatePhasingSave() {

    if (!this.selectedZone) {

        this.showToast(
            'Validation',
            'Please select a Zone.',
            'warning'
        );

        return;
    }

    const selectedIds = [...this.selectedRowIds];

    if (!selectedIds.length) {

        this.showToast(
            'Validation',
            'Please select at least one Unit.',
            'warning'
        );

        return;
    }

    this.isLoading = true;

    try {

        const response = await updateHandoverDetailZone({
            businessProcessIds: selectedIds,
            zoneName: this.selectedZone
        });

        if (response.success) {

            this.showToast(
                'Success',
                response.message,
                'success'
            );

            /*
             * Remove successfully updated records
             * from the CSV table.
             */
            this.removeUpdatedCsvRecords(selectedIds);

            /*
             * Close modal.
             */
            this.showUpdatePhasingModal = false;
            this.selectedZone = '';

        } else {

            this.showToast(
                'Error',
                response.message,
                'error'
            );
        }

    } catch (error) {

        console.error(
            'Update Phasing Error:',
            error
        );

        this.showToast(
            'Error',
            error?.body?.message ||
            'Unable to update the Handover Detail.',
            'error'
        );

    } finally {

        this.isLoading = false;
    }
}

removeUpdatedCsvRecords(updatedIds) {

    const updatedIdSet = new Set(updatedIds);

    /*
     * Remove from all records.
     */
    this.allRecords = this.allRecords.filter(
        row => !updatedIdSet.has(row.Id)
    );

    /*
     * Recalculate pagination.
     */
    if (this.allRecords.length > 0) {

        this.totalPages = Math.ceil(
            this.allRecords.length / this.pageSize
        );

        /*
         * If the current page no longer exists,
         * move back to the last available page.
         */
        if (this.pageNumber > this.totalPages) {

            this.pageNumber = this.totalPages;
        }

        this.updatePageData();

        this.showTable = true;
        this.showNoRecords = false;

    } else {

        this.records = [];
        this.totalPages = 0;
        this.pageNumber = 1;

        this.showTable = false;
        this.showNoRecords = true;
    }
}

//BCC Letter Upload

handleUploadBCCLetter() {

    const selectedIds = [...this.selectedRowIds];

    if (!selectedIds.length) {
        this.showToast(
            'Warning',
            'Please select at least one Business Process.',
            'warning'
        );
        return;
    }

    // First selected BP is the temporary upload location
    this.bccUploadRecordId = selectedIds[0];

    this.bccUploadedFileName = null;
    this.showBCCLetterModal = true;
}

async handleBCCUploadFinished(event) {

    const uploadedFiles = event.detail.files;

    if (!uploadedFiles || uploadedFiles.length === 0) {
        this.showToast(
            'Error',
            'No file was uploaded.',
            'error'
        );
        return;
    }

    const contentDocumentId = uploadedFiles[0].documentId;

    const selectedIds = [...this.selectedRowIds];

    this.bccUploadedFileName = uploadedFiles[0].name;

    this.isLoading = true;

    try {

        const response = await uploadBCCLetter({
            businessProcessIds: selectedIds,
            contentDocumentId: contentDocumentId
        });

        if (response.success) {

            this.showToast(
                'Success',
                response.message,
                'success'
            );

            this.showBCCLetterModal = false;
            this.bccUploadRecordId = null;
            this.bccUploadedFileName = null;

            this.handleClear();

        } else {

            this.showToast(
                'Error',
                response.message,
                'error'
            );
        }

    } catch (error) {

        console.error('BCC Letter Upload Error:', error);

        this.showToast(
            'Error',
            error?.body?.message ||
            'Unable to upload BCC Letter.',
            'error'
        );

    } finally {

        this.isLoading = false;
    }
}

handleCloseBCCLetterModal() {

    if (this.isLoading) {
        return;
    }

    this.showBCCLetterModal = false;

    this.bccUploadRecordId = null;

    this.bccUploadedFileName = null;
}

}