import { UNIT_SEARCH_BASE_COLUMNS } from "c/modonEgyptConstants";

export const CONSTANTS = {
  EMPTY_STRING: '',

  STANDARD_PLAN_ERROR_TITLE_GENERATE: 'Error in Standard Payment Plan',
  STANDARD_PLAN_ERROR_FALLBACK_MSG: 'Unknown Error',
  STANDARD_PLAN_PLACEHOLDER_SELECT_PAYMENT_PLAN: 'Select Payment Plan',
  STANDARD_PLAN_LABEL_PAYMENT_DETAILS: 'Payment Details',
  STANDARD_PLAN_LABEL_EXACT_BOOKING_DATE: 'Exact Booking Date',
  STANDARD_PLAN_INPUT_NAME_EXACT_BOOKING_DATE: 'extactBookingDate',

  STANDARD_PLAN_EVENT_PLAN_CHANGE: 'planchange',
  STANDARD_PLAN_EVENT_DATE_CHANGE: 'datechange',

  STANDARD_PLAN_COLUMNS: [...UNIT_SEARCH_BASE_COLUMNS],

  // Events bubbled to parent (Payment Plan Manager / Unit Search)
  STANDARD_PLAN_EVENT_STD_PLAN_READY: 'standardplanready',

  STANDARD_PLAN_PAYMENT_KEYWORD_8_YEAR: '8 year',
  STANDARD_PLAN_PAYMENT_KEYWORD_8_YEARS: '8 Years',
  STANDARD_PLAN_PAYMENT_KEYWORD_6_YEAR: '6 year',
  STANDARD_PLAN_PAYMENT_KEYWORD_4_YEAR: '4 year',
  STANDARD_PLAN_PAYMENT_KEYWORD_CASH: 'cash',
  STANDARD_PLAN_CURRENCY_EGP: 'EGP',
  STANDARD_PLAN_CURRENCY_USD: 'USD',
  STANDARD_PLAN_CURRENCY_AED: 'AED',

  STANDARD_PLAN_ERROR_INVALID_EXACT_BOOKING_DATE_INPUT_TITLE: 'Invalid Exact Booking Date',
  STANDARD_PLAN_ERROR_INVALID_EXACT_BOOKING_DATE_INPUT_MESSAGE: 'Exact Booking Date cannot be in the future',
};